apps/course_reg/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^addCourse$', views.addCourse, name='add_class'),
    url(r'^removeCourse/(?P<id>\d+)$', views.removeCourse, name="remove"),
    url(r'^confirmRemove/(?P<id>\d+)$', views.confirmRemove, name="confirm")
]

courses/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.course_reg.urls', namespace='courses'))
]

apps/course_reg/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Courses(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

apps/course_reg/views.py
from django.shortcuts import render, redirect
from .models import Courses

def index(request):
    context = {
        'course_info':Courses.objects.all()
    }
    return render(request,'course_reg/index.html', context)

def addCourse(request):
    if request.method == 'POST':
        Courses.objects.create(name = request.POST['course_name'], description = request.POST['course_descript'])

    return redirect('courses:index')

def removeCourse(request, id):
    context = {
        "course_info": Courses.objects.get(id=id)
    }
    return render(request, 'course_reg/remove.html', context)

def confirmRemove(request, id):
    deleteMe = Courses.objects.get(id=id)
    deleteMe.delete()
    return redirect('courses:index')

apps/course_reg/templates/course_reg/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Course Registration</title>
  </head>
  <body>
    <div id="wrapper">
      <div id="add_course">
        <h1>Add a new course</h1>
        <form action="{% url 'courses:add_class' %}" method="post">
          {% csrf_token %}
          <label for="name">Name:</label>
          <input type="text" id="name" name="course_name">
          <label for="descript">Description:</label>
          <input type="textarea" id="descript" name="course_descript">
          <input type="submit" name= "" value="Add Course"></input>
        </form>
      </div>
      <div id="course_list">
        <h2>All courses</h2>
        <table>
          <tr>
            <th>Course Name</th>
            <th>Description</th>
            <th>Date Added</th>
            <th>Actions</th>
          </tr>
            {% for courses in course_info %}
          <tr>
            <td>{{ courses.name }}</td>
            <td>{{ courses.description }}</td>
            <td>{{ courses.created_at }}</td>
            <td><a href="{% url 'courses:remove' id=courses.id%}">Remove</a>
            </td>
          </tr>
            {% endfor %}
          </table>
      </div>
    </div>
  </body>
</html>

apps/course_reg/templates/course_reg/remove.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Remove course</title>
  </head>
  <body>
    <h1> Are you sure you want to delete the following course?</h1>
    <p>Name: {{ course_info.name }}</p>
    <p>Description: {{ course_info.description }}</p>
    <form action='/'>
    {% csrf_token %}
      <input type="submit" value ="No">
    </form>
    <form action="{% url 'courses:confirm' id=course_info.id%}">
      {% csrf_token %}
      <input type="submit" value ="Yes, I want to delete this">
    </form>
  </body>
</html>